import { describe, expect, test } from "bun:test"
import { readFile } from "node:fs/promises"
import type { Plugin } from "@opencode/plugin"
import type { OhMyOpenCodeConfig } from "../config"
import {
	buildV2CompactionPrompt,
	hasV2SummarySection,
	preemptiveInputLimit,
	registerV2CompactionModelOverride,
	registerV2PreemptiveCompaction,
	registerV2ToolOutputTruncator,
	resolveV2CompactionModel,
	serializeV2CompactionTranscript,
} from "./long-conversation"

type Model = { providerID: string; id: string; enabled?: boolean; limit: { context: number; input?: number; output: number }; variants?: Array<{ id: string }> }

function makeContext(options: {
	models?: Model[]
	session?: Record<string, unknown>
	context?: unknown[]
	generated?: string
	generateError?: Error
} = {}) {
	const models = options.models ?? [{ providerID: "omoqa", id: "qa-model", limit: { context: 200_000, output: 8_192 } }]
	const sessionHooks = new Map<string, (input: any) => unknown>()
	const toolHooks = new Map<string, (input: any) => unknown>()
	let transform: ((editor: any) => void) | undefined
	const generateCalls: Array<{ prompt: string; model: unknown }> = []
	const updates: Array<{ key: string; input?: number }> = []
	let reloads = 0
	const ctx = {
		location: { directory: "/project" },
		session: {
			hook: async (name: string, callback: (input: any) => unknown) => {
				sessionHooks.set(name, callback)
				return { dispose: async () => { sessionHooks.delete(name) } }
			},
			get: async ({ sessionID }: { sessionID: string }) => ({ id: sessionID, model: { providerID: "omoqa", id: "qa-model" }, ...options.session }),
			context: async () => options.context ?? [],
		},
		tool: {
			hook: async (name: string, callback: (input: any) => unknown) => {
				toolHooks.set(name, callback)
				return { dispose: async () => { toolHooks.delete(name) } }
			},
		},
		model: {
			list: async () => ({ data: models }),
			reload: async () => {
				reloads++
				transform?.(editor)
			},
			transform: async (callback: (editor: any) => void) => {
				transform = callback
				callback(editor)
				return { dispose: async () => { transform = undefined } }
			},
		},
		generate: {
			text: async (input: { prompt: string; model: unknown }) => {
				generateCalls.push(input)
				if (options.generateError) throw options.generateError
				return { text: options.generated ?? "## Objective\n- summarized by compaction model" }
			},
		},
		event: { subscribe: ({ signal }: { signal: AbortSignal }) => (async function* () { await new Promise((resolve) => signal.addEventListener("abort", resolve, { once: true })) })() },
	}
	const editorModels = models.map((model) => ({ ...model, limit: { ...model.limit } }))
	const editor = {
		list: () => editorModels,
		update: (providerID: string, id: string, update: (draft: Model) => void) => {
			const model = editorModels.find((entry) => entry.providerID === providerID && entry.id === id)
			if (!model) return
			update(model)
			updates.push({ key: `${providerID}/${id}`, input: model.limit.input })
		},
	}
	return { ctx: ctx as unknown as Plugin.Context, sessionHooks, toolHooks, generateCalls, updates, editorModels, reloads: () => reloads }
}

describe("v2 long-conversation policy", () => {
	test("preemptive threshold lowers the native input limit to 78% of context plus the host buffer", async () => {
		expect(preemptiveInputLimit(200_000)).toBe(176_000)
		expect(preemptiveInputLimit(0)).toBeUndefined()
		const { ctx, editorModels } = makeContext({ models: [
			{ providerID: "omoqa", id: "qa-model", limit: { context: 200_000, output: 8_192 } },
			{ providerID: "omoqa", id: "strict", limit: { context: 200_000, input: 100_000, output: 8_192 } },
		] })
		const cleanup = await registerV2PreemptiveCompaction(ctx, { experimental: { preemptive_compaction: true } } as OhMyOpenCodeConfig)
		expect(editorModels[0]!.limit.input).toBe(176_000)
		expect(editorModels[1]!.limit.input).toBe(100_000)
		await cleanup()
	})

	test("preemptive compaction is opt-in and honors disabled_hooks", async () => {
		const disabledByDefault = makeContext()
		await (await registerV2PreemptiveCompaction(disabledByDefault.ctx, {} as OhMyOpenCodeConfig))()
		expect(disabledByDefault.editorModels[0]!.limit.input).toBeUndefined()
		const disabled = makeContext()
		await (await registerV2PreemptiveCompaction(disabled.ctx, { experimental: { preemptive_compaction: true }, disabled_hooks: ["preemptive-compaction"] } as OhMyOpenCodeConfig))()
		expect(disabled.editorModels[0]!.limit.input).toBeUndefined()
	})

	test("compaction model override supplies a host-format summary generated by the configured model", async () => {
		const { ctx, sessionHooks, generateCalls } = makeContext({ models: [
			{ providerID: "omoqa", id: "qa-model", limit: { context: 200_000, output: 8_192 } },
			{ providerID: "omoqa", id: "qa-compactor", limit: { context: 100_000, output: 8_192 }, variants: [{ id: "high" }] },
		] })
		const config = { agents: { sisyphus: { compaction: { model: "omoqa/qa-compactor", variant: "high" } } } } as unknown as OhMyOpenCodeConfig
		expect(resolveV2CompactionModel(config, "sisyphus")).toEqual({ model: { providerID: "omoqa", id: "qa-compactor", variant: "high" } })
		expect(resolveV2CompactionModel(config, "atlas")).toBeUndefined()
		const cleanup = await registerV2CompactionModelOverride(ctx, config)
		const input: Record<string, unknown> = {
			sessionID: "ses-1",
			agent: "sisyphus",
			model: { providerID: "omoqa", id: "qa-model" },
			system: [{ type: "text", text: "OMO_STATE task_id ses-child" }],
			messages: [
				{ role: "user", content: [{ type: "text", text: "Fix the parser" }] },
				{ role: "assistant", content: [{ type: "tool-call", name: "grep", input: { pattern: "x" } }] },
				{ role: "tool", content: [{ type: "tool-result", result: { type: "content", value: [{ type: "text", text: "match.ts:1" }] } }] },
			],
			tools: {},
			options: {},
		}
		await sessionHooks.get("compaction")!(input)
		expect(generateCalls).toHaveLength(1)
		expect(generateCalls[0]!.model).toEqual({ providerID: "omoqa", id: "qa-compactor", variant: "high" })
		expect(generateCalls[0]!.prompt).toContain("OMO_STATE task_id ses-child")
		expect(generateCalls[0]!.prompt).toContain("[User]: Fix the parser")
		expect(generateCalls[0]!.prompt).toContain("[Tool result]: match.ts:1")
		expect(generateCalls[0]!.prompt).toContain("## Objective")
		expect(input.result).toMatchObject({ summary: "## Objective\n- summarized by compaction model", metadata: { omoCompactionModel: "omoqa/qa-compactor#high" } })
		await cleanup()
	})

	test("compaction model falls back to the host session model on invalid output, failure or an unavailable model", async () => {
		const config = { agents: { sisyphus: { compaction: { model: "omoqa/qa-compactor" } } } } as unknown as OhMyOpenCodeConfig
		const models: Model[] = [
			{ providerID: "omoqa", id: "qa-model", limit: { context: 200_000, output: 8_192 } },
			{ providerID: "omoqa", id: "qa-compactor", limit: { context: 100_000, output: 8_192 } },
		]
		const base = { sessionID: "ses-1", agent: "sisyphus", model: { providerID: "omoqa", id: "qa-model" }, system: [], messages: [{ role: "user", content: "hi" }], tools: {}, options: {} }
		for (const variant of [{ generated: "no headings here" }, { generateError: new Error("provider down") }, { models: models.slice(0, 1) }]) {
			const { ctx, sessionHooks } = makeContext({ models, ...variant })
			const cleanup = await registerV2CompactionModelOverride(ctx, config)
			const input: Record<string, unknown> = { ...base }
			await sessionHooks.get("compaction")!(input)
			expect(input.result).toBeUndefined()
			await cleanup()
		}
		const same = makeContext({ models })
		const cleanup = await registerV2CompactionModelOverride(same.ctx, { agents: { sisyphus: { compaction: { model: "omoqa/qa-model" } } } } as unknown as OhMyOpenCodeConfig)
		const input: Record<string, unknown> = { ...base }
		await same.sessionHooks.get("compaction")!(input)
		expect(same.generateCalls).toHaveLength(0)
		await cleanup()
		const unconfigured = makeContext({ models })
		await (await registerV2CompactionModelOverride(unconfigured.ctx, {} as OhMyOpenCodeConfig))()
		expect(unconfigured.sessionHooks.has("compaction")).toBe(false)
	})

	test("compaction prompt mirrors the host template and update wording", () => {
		expect(buildV2CompactionPrompt(false)).toContain("You MUST summarize the conversation above")
		expect(buildV2CompactionPrompt(true)).toContain("Update the existing checkpoint")
		expect(hasV2SummarySection("## Next Move\n1. x")).toBe(true)
		expect(hasV2SummarySection("Objective: x")).toBe(false)
		const serialized = serializeV2CompactionTranscript({ system: [{ type: "text", text: "S" }], messages: [{ role: "assistant", content: [{ type: "text", text: "A" }] }] as never })
		expect(serialized).toEqual({ system: "S", transcript: ["[Assistant]: A"] })
	})

	test("tool output truncator bounds eligible outputs by remaining context and retains the full output", async () => {
		const { ctx, toolHooks } = makeContext({ context: [{ type: "assistant", tokens: { input: 190_000, output: 1_000, cache: { read: 0, write: 0 } } }] })
		const cleanup = await registerV2ToolOutputTruncator(ctx, {} as OhMyOpenCodeConfig)
		const big = Array.from({ length: 4_000 }, (_, index) => `line ${index} ${"x".repeat(20)}`).join("\n")
		const result: { content: unknown; metadata?: Record<string, unknown> } = { content: [{ type: "text", text: big }] }
		await toolHooks.get("execute.after")!({ tool: "grep", sessionID: "ses-1", status: "completed", result })
		expect(result.metadata?.truncated).toBe(true)
		const maxTokens = (result.metadata?.omoTruncation as { maxTokens: number }).maxTokens
		expect(maxTokens).toBe(4_500)
		const text = (result.content as Array<{ text: string }>)[0]!.text
		expect(text.length).toBeLessThan(big.length)
		expect(text).toContain("more lines truncated due to context window limit")
		expect(await readFile(String(result.metadata?.outputPath), "utf8")).toBe(big)

		const read: { content: unknown; metadata?: Record<string, unknown> } = { content: [{ type: "text", text: big }] }
		await toolHooks.get("execute.after")!({ tool: "read", sessionID: "ses-1", status: "completed", result: read })
		expect(read.metadata).toBeUndefined()
		await cleanup()
	})

	test("tool output truncator suppresses output at exhaustion, supports truncate-all and honors disabled_hooks", async () => {
		const exhausted = makeContext({ context: [{ type: "assistant", tokens: { input: 199_000, output: 1_000, cache: { read: 0, write: 0 } } }] })
		const cleanup = await registerV2ToolOutputTruncator(exhausted.ctx, { experimental: { truncate_all_tool_outputs: true } } as OhMyOpenCodeConfig)
		const result: { content: unknown; metadata?: Record<string, unknown> } = { content: [{ type: "text", text: "short output" }] }
		await exhausted.toolHooks.get("execute.after")!({ tool: "shell", sessionID: "ses-1", status: "completed", result })
		expect((result.content as Array<{ text: string }>)[0]!.text).toContain("[Output suppressed - context window exhausted]")
		await cleanup()
		const small = makeContext()
		const smallCleanup = await registerV2ToolOutputTruncator(small.ctx, {} as OhMyOpenCodeConfig)
		const untouched: { content: unknown; metadata?: Record<string, unknown> } = { content: [{ type: "text", text: "small" }] }
		await small.toolHooks.get("execute.after")!({ tool: "webfetch", sessionID: "ses-1", status: "completed", result: untouched })
		expect(untouched.metadata).toBeUndefined()
		await smallCleanup()
		const disabled = makeContext()
		await (await registerV2ToolOutputTruncator(disabled.ctx, { disabled_hooks: ["tool-output-truncator"] } as OhMyOpenCodeConfig))()
		expect(disabled.toolHooks.has("execute.after")).toBe(false)
	})
})

describe("v2 compaction overflow guard", () => {
	test("aggressive truncation shrinks the largest compaction tool results until the request fits", async () => {
		const { boundV2CompactionTranscript } = await import("./long-conversation")
		const huge = "y".repeat(400_000)
		const small = "z".repeat(1_000)
		const input = {
			system: [{ type: "text" as const, text: "system" }],
			messages: [
				{ role: "user", content: [{ type: "text", text: "go" }] },
				{ role: "tool", content: [{ type: "tool-result", result: { type: "content", value: [{ type: "text", text: huge }] } }] },
				{ role: "tool", content: [{ type: "tool-result", result: { type: "text", value: small } }] },
			],
		}
		const count = boundV2CompactionTranscript(input as never, 100_000, 8_192)
		expect(count).toBe(1)
		const bounded = (input.messages[1]!.content[0] as { result: { value: Array<{ text: string }> } }).result.value[0]!.text
		expect(bounded.length).toBeLessThan(huge.length)
		expect(bounded).toContain("Tool output truncated from 400000 characters for compaction")
		expect((input.messages[2]!.content[0] as { result: { value: string } }).result.value).toBe(small)
		expect("system".length + input.messages.reduce((sum, message) => sum + JSON.stringify(message.content).length, 0)).toBeLessThanOrEqual((100_000 - 8_192 - 20_000) * 4)
		expect(boundV2CompactionTranscript(input as never, 100_000, 8_192)).toBe(0)
	})

	test("the overflow guard is opt-in and only edits the compaction request", async () => {
		const { registerV2CompactionOverflowGuard } = await import("./long-conversation")
		const off = makeContext()
		await (await registerV2CompactionOverflowGuard(off.ctx, {} as OhMyOpenCodeConfig))()
		expect(off.sessionHooks.has("compaction")).toBe(false)
		const on = makeContext({ models: [{ providerID: "omoqa", id: "qa-model", limit: { context: 50_000, output: 4_096 } }] })
		const cleanup = await registerV2CompactionOverflowGuard(on.ctx, { experimental: { aggressive_truncation: true } } as OhMyOpenCodeConfig)
		const input = { sessionID: "s", agent: "sisyphus", model: { providerID: "omoqa", id: "qa-model" }, system: [], messages: [{ role: "tool", content: [{ type: "tool-result", result: { type: "text", value: "q".repeat(300_000) } }] }] }
		await on.sessionHooks.get("compaction")!(input)
		expect((input.messages[0]!.content[0]!.result as { value: string }).value.length).toBeLessThan(300_000)
		await cleanup()
	})
})
